CREATE TABLE Query (
Name VARCHAR(30) NOT NULL,
email VARCHAR(50) NOT NULL,
Query VARCHAR(30) NOT NULL,
email VARCHAR(50),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)